import React, { ReactNode } from "react";
import localFont from "next/font/local";
import { TasksProvider } from "@/context/taskContext";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Cours Dev Cloud TODO List",
  description: "Generated by tadayoshi123",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TasksProvider>{children}</TasksProvider>
      </body>
    </html>
  );
}